# Pandas Foundation

(uses lists to manipulate the data)

In [196]:
import pandas as pd

features of pandas are:
Heterogeneous (Mixed datatype unlike numpy),
Label based system(row, index),
Tabular data , time series are primary uses,
Built in NaN support,

In [197]:
a = pd.Series([1, 2, 3, 4, 5])

#default index for dict
print(a) #Default is with labels or index starting from 0
print("Series values:", s.values)

0    1
1    2
2    3
3    4
4    5
dtype: int64
Series values: [1 2 3 4 5]

Custom indexing

In [198]:
s = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e'])
print(s) #Custom index
#Accessing value using custom index
print(s['a']) 
print(s[0])

a    1
b    2
c    3
d    4
e    5
dtype: int64
1
1

C:\Users\saikiran\AppData\Local\Temp\ipykernel_27336\2223972200.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])

Series from Dictionary

In [199]:
#series of python to pandaas
data = {'Maths': 90, 'Science': 85, 'English': 85}
print(data)
marks = pd.Series(data)
print(marks)
#why no index here? because it is a dict, so it will take the keys as index and values as values

{'Maths': 90, 'Science': 85, 'English': 85}
Maths      90
Science    85
English    85
dtype: int64

In [200]:
data = {
    "Name": ["Alice", "Bob", "Charlie"],
    "Age": [25, 30, 35],
    "Marks": [85, 90, 95]
}
print(data) #python dictionary
print(type(data))
#convert to pandas dataframe
marks = pd.DataFrame(data) #pandas automatically adds a default index starting from 0 by default. this is called RangeIndex

print(marks)

{'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35], 'Marks': [85, 90, 95]}
<class 'dict'>
      Name  Age  Marks
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95

In [201]:
#we can also add custom index in pandas dataframe
marks = pd.DataFrame(data, 
        index=['a', 'b', 'c']
        )
print(marks)

      Name  Age  Marks
a    Alice   25     85
b      Bob   30     90
c  Charlie   35     95

In [202]:
marks.set_index("Name", inplace=True)
#if we are setting inplace as true it means we are changing the original dataframe, 
# if we are not setting inplace as true it means we are creating a new dataframe with the new index and the original dataframe will remain unchanged

In [203]:
df = pd.DataFrame(
    {
        "Name": ["Alice", "Bob", "Charlie","Aria", "David", "Eve"],
        "Age": [25, 30, 35,15,40,45],
        "Marks": [85, 90, 95, 75,99, 88]
    }
)
print(df)
df.head()
#f.tail(2)

      Name  Age  Marks
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3     Aria   15     75
4    David   40     99
5      Eve   45     88

      Name  Age  Marks
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3     Aria   15     75
4    David   40     99

In [204]:
df.tail(2)

    Name  Age  Marks
4  David   40     99
5    Eve   45     88

In [205]:
df.shape

(6, 3)

In [206]:

df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [207]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    6 non-null      object
 1   Age     6 non-null      int64
 2   Marks   6 non-null      int64
dtypes: int64(2), object(1)
memory usage: 276.0+ bytes

In [208]:
df.describe()

             Age      Marks
count   6.000000   6.000000
mean   31.666667  88.666667
std    10.801234   8.358628
min    15.000000  75.000000
25%    26.250000  85.750000
50%    32.500000  89.000000
75%    38.750000  93.750000
max    45.000000  99.000000

Selecting the data

In [209]:
df[["Name", "Marks"]]

      Name  Marks
0    Alice     85
1      Bob     90
2  Charlie     95
3     Aria     75
4    David     99
5      Eve     88

Filtering in Pandas
(Important topic where we can expect some Q's)

In [210]:
df[df["Marks"] > 90]

      Name  Age  Marks
2  Charlie   35     95
4    David   40     99

In [211]:
#multiple conditions
df[(df["Marks"] > 90) & (df["Age"] > 30)]

      Name  Age  Marks
2  Charlie   35     95
4    David   40     99

Sorting + Value counts

In [212]:
df.sort_values("Marks")

      Name  Age  Marks
3     Aria   15     75
0    Alice   25     85
5      Eve   45     88
1      Bob   30     90
2  Charlie   35     95
4    David   40     99

In [213]:
#for descending order
df.sort_values("Marks", ascending=False)

      Name  Age  Marks
4    David   40     99
2  Charlie   35     95
1      Bob   30     90
5      Eve   45     88
0    Alice   25     85
3     Aria   15     75

In [214]:
df["Age"].value_counts()

Age
25    1
30    1
35    1
15    1
40    1
45    1
Name: count, dtype: int64

# handling missing values

In [215]:
#updating the dataset null values

df = pd.DataFrame(
    {
        "Name" : ["Aman","Saurav","Karan","Shubham",None,"Sameer"],
        "Age": [22, 23, None, 22, 25, 26],
        "Marks": [88, 92, 95, None, 85, None]

    }
)

df

      Name   Age  Marks
0     Aman  22.0   88.0
1   Saurav  23.0   92.0
2    Karan   NaN   95.0
3  Shubham  22.0    NaN
4     None  25.0   85.0
5   Sameer  26.0    NaN

In [216]:
df.isnull()
#prints true is null and false if not null

    Name    Age  Marks
0  False  False  False
1  False  False  False
2  False   True  False
3  False  False   True
4   True  False  False
5  False  False   True

In [217]:
df.isnull().sum()
#counting the missing values in each column

Name     1
Age      1
Marks    2
dtype: int64

In [218]:
#to drop all the rows with missing values
df.dropna()
df

      Name   Age  Marks
0     Aman  22.0   88.0
1   Saurav  23.0   92.0
2    Karan   NaN   95.0
3  Shubham  22.0    NaN
4     None  25.0   85.0
5   Sameer  26.0    NaN